### ISSUE TITLE
Getting error while trying to create scaffold and migrate option

### ISSUE THREAD

**Issue by AjithLalps** [pilabrem/laravel-code-generator-ui#1]
When running scaffold with migration option after creating a table, getting the error `The command "create:scaffold" does not exist.`

laravel-code-generator-ui: ^0.4.0
laravel version: 5.8.*
php version: 7.3

**Comment by hermben** [comment]
Hello,
This package need crestapps/laravel-code-generator to work. Install it with this command : 
`composer require crestapps/laravel-code-generator="~2.4" --dev`

**Comment by AjithLalps** [comment]
There is a dependency on the package on the composer.json file
```
 "require-dev": {
        "crestapps/laravel-code-generator": "~2.4"
    },
```
then why we need to install the package separately?

**Comment by pilabrem** [comment]
> There is a dependency on the package on the composer.json file
> 
> ```
>  "require-dev": {
>         "crestapps/laravel-code-generator": "~2.4"
>     },
> ```
> 
> then why we need to install the package separately?

Composer ignores package require-dev packages on installation. This problem is solved in the last version of the package. You can try the latest version 0.4.5.
